language: python
python:
  - "2.7"
before_install:
  - sudo apt-get install rdiff-backup
  - pip install pep8
  - pip install pyflakes
  - pip install coverage
  - pip install coveralls
install:
  - python setup.py install
before_script:
  - make verify
script:
  make test
after_success:
  coveralls
notifications:
  slack: smartfile:tbDIPzVJIPBpSz29kQw6b8RQ
